### ISSUE TITLE
ailed to read frame size: Could not seek to 1026

### ISSUE THREAD

**Issue by gersooonn** [rany2/edge-srt-to-speech#24]
It stopped working for me, now I'm displaying this error in all the .srt files I use
[mp3 @ 0x57ff4b431c80] Failed to read frame size: Could not seek to 1026.
/tmp/tmplxc7l66i/15.mp3: Invalid argument
Traceback (most recent call last):
  File "/content/drive/MyDrive/edge-srt-to-speech/src/edge_srt_to_speech/__main__.py", line 346, in <module>
    main()
  File "/content/drive/MyDrive/edge-srt-to-speech/src/edge_srt_to_speech/__main__.py", line 332, in main
    asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/drive/MyDrive/edge-srt-to-speech/src/edge_srt_to_speech/__main__.py", line 251, in _main
    last_end += get_duration(j)
  File "/content/drive/MyDrive/edge-srt-to-speech/src/edge_srt_to_speech/__main__.py", line 39, in get_duration
    duration = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1', '/tmp/tmplxc7l66i/15.mp3']' returned non-zero exit status 1.

![image](https://github.com/rany2/edge-srt-to-speech/assets/128495179/bf74df7d-96fc-4f21-bcdf-27f9f12db124)

**Comment by rany2** [comment]
Even if you install the version from master?

**Comment by gersooonn** [comment]
I'll try it here and see if it works.
One question, sometimes in the generated audio section, the voice accelerates very quickly, making it impossible to understand, how can I disturb this?

**Comment by gersooonn** [comment]
I can't, I sent you the link to the colab I'm using
https://colab.research.google.com/drive/13qbG1X-IyJtb6rAOGXAII7O1jo2rLkiI?usp=sharing

![image](https://github.com/rany2/edge-srt-to-speech/assets/128495179/02684f12-9e82-493b-afd5-a0d0c02c77fa)

**Comment by rany2** [comment]
This only happened after the upgrade to edge-tts 6.1.12?

**Comment by gersooonn** [comment]
It seems so, after edge-tts 6.1.12 was uploaded, I couldn't get it to run. Did you take a look at this Colab I sent you?

**Comment by rany2** [comment]
Can you share your `legenda.srt`? I can't reproduce.

**Comment by gersooonn** [comment]
[legenda.srt.txt](https://github.com/user-attachments/files/15533755/legenda.srt.txt)
I sent it to you, you have to remove the .txt section because here on Github it doesn't accept .srt

**Comment by rany2** [comment]
I can't reproduce it still... maybe Colab is the one having its IP blocked?
